# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Em_Wfv33C4EaHw2RrBwynwLNYHSXcD-M
"""

from bs4 import BeautifulSoup
import requests
from urllib.request import urlopen
from lxml import html 


#пишешь по аналогии как я потому что так удобно ориентироваться
#все пометки, которые я делал например сдлеать словарь и тп ничего не делай



# это функция кода, т.е. выводит код lxml/html страницы

def kod(link):
  url = link
  headers = {'Content-Type': 'text/html',}
  response = requests.get(url, headers=headers)
  tree = html.fromstring(response.content)
  return tree

tree = kod("https://physics.itmo.ru/ru")


# Parsing the page
# (We need to use page.content rather than 
# page.text because html.fromstring implicitly
# expects bytes as input.)




####### Главная страница #######

# Get element using XPath

# Новости 

opisanie_news = tree.xpath('//div[@class="node--title"]/text()')
photo_news = tree.xpath('//img[@class="img-responsive"]/@src')
#//img[@class='photo-large']/@src

# print(opisanie_news)
# print(photo_news)


# надо писать окончательный путь
# Семинары 

semianrs_photo = tree.xpath('//img[@class="img-responsive"]/@src')
semianars_topic1 = tree.xpath('//div[@class="seminar-type-value"]/text()')
seminars_names_speakers = tree.xpath('//div[@class="external-speaker-wrapper"]/text()')
semianars_topic2 = tree.xpath('//div[@class="speaker-talk-name"]/text()')
semianars_time_date = tree.xpath('//div[@class="dte"]/text()')
semianars_time_time = tree.xpath('//div[@class="tme"]/text()')

# сделать функцию tree.path...


###### Сотрудники ######

tree = kod("https://physics.itmo.ru/ru/people")
sotrudniki_photo = tree.xpath('//img[@class="img-responsive"]/@src')
sotrudniki_name1 = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
sotrudniki_name2 = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')
sotrudniki_about = tree.xpath('//div[@class="field field--name-main-position field--type-entity-reference field--label-hidden field--item"]/text()')
sotrudniki_about_links = tree.xpath('//div[@class="node--wrap"]/@src')
# поискать


###### видео ######

tree = kod("https://physics.itmo.ru/ru/media/video")
videos_video = tree.xpath('//iframe[@width="854"]/@src')
videos_about = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
videos_picture = []


a = "https://i.ytimg.com/vi_webp/"
c = "/sddefault.webp"

for i in range(len(videos_video)):
  videos_video[i] = str(videos_video[i])
  j = 30
  b = ""
  while videos_video[i][j] != "?":
    b = b + videos_video[i][j]
    j += 1 
  videos_picture.append(a + b + c)

###### вакансии ######

#создаётся словарь с названием вакансией и описанием 

tree = kod("https://physics.itmo.ru/ru/vacancies")
vacancies_name = tree.xpath('//a[@hreflang="ru"]/text()')
vacancies_topic = tree.xpath('//h3/text()')


####### софт ########
# создать словарь 

tree = kod("https://physics.itmo.ru/ru/soft")
soft_name = tree.xpath('//span[@class="field-content"]/text()')
soft_author = tree.xpath('//a[@hreflang="ru"]/text()')
soft_links = tree.xpath('//div[@class="field-content"]/@src') #не работает


####### сми ########




def kod(link):
  url = link
  headers = {'Content-Type': 'text/html',}
  response = requests.get(url, headers=headers)
  tree = html.fromstring(response.content)
  return tree

def parsing(link):
  url = link
  headers = {'Content-Type': 'text/html',}
  response = requests.get(url, headers=headers)
  soup = BeautifulSoup(response.text, "html.parser")
  return soup

def poisk(c):
  n = ""
  i = 24
  a = str(re.search("field field--name", c))
  if a != "None":
    while a[i] != ",":
      n += a[i]
      i += 1
    n = int(n)
    return n
  else:
    return "1"  

def udalenie(c, i):
  c = c[:poisk(c)] + "g" + c[poisk(c)+1:]
  return c

def dobavlenie(soup):
  i = poisk(soup)
  while soup[i] != ">":
    i += 1
  i += 1
  c = ""
  while soup[i] != "<":
    c += soup[i]
    i += 1
  # print(c)
  return c 

def links(soup):
  n = ""
  i = poisk(soup) - 35
  while soup[i] != "=":
    i -= 1
  i += 2
  while soup[i] != ">":
    n += soup[i]
    i += 1
  for i in range(2):
    n[:len(n)-1]
  return n



soup = str(parsing("https://physics.itmo.ru/ru/media/press"))
# tree = kod("https://physics.itmo.ru/ru/media/press")
# a = tree.xpath('//div[@class="field field--name"]/text()')
# a = str(a[0])

kods = []

# poisk(soup) != "1"


smi_about = []
smi_links = []

for i in range(17):
  c = ""
  smi_links.append(links(soup))
  while dobavlenie(soup) != '':
    # kods.append(poisk(soup))
    # kods.append(dobavlenie(soup))
    c += "<br><br>" + dobavlenie(soup)
    soup = udalenie(soup, poisk(soup))
  kods.append(c)
  soup = udalenie(soup, poisk(soup))  

smi_about = kods


###### научные группы #######


def im(a, k):
  i = 37
  b = ""
  g = ""
  while a[k][i] != "\n":
    b += a[k][i]
    i += 1
  i = 75
  while a[k][i] != "\n":
    g += a[k][i]
    i += 1
  b = "Группа " + b + " " + g
  return b


a = []
group_names = []
group_name = [] #название группы 

tree = kod("https://physics.itmo.ru/ru/research-groups")
a = tree.xpath('//div[@class="research-group-group-name"]/text()')
group_group = tree.xpath('//div[@class="views-field views-field-title"]/span[@class="field-content"]/a[@class="use-ajax"]/div[@class="research-group-group-name"]/text()')
group_links = tree.xpath('//span[@class="field-content"]/a/@href')

for k in range(len(a)):
  group_name.append(im(a, k))


names = []
surnames = []
group_full_names = [] # имя и фамилия персон
group_full_photo = [] # фото персон
rank = []


for i in range(len(group_links)):
  tree = kod("https://physics.itmo.ru/ru/" + group_links[i])
  group_names = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
  group_surnames = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')
  group_photo = tree.xpath('//div[@class="field field--name-photo field--type-image field--label-hidden field--item"]/img/@src')
  names.append(group_names)
  surnames.append(group_surnames)
  rank.append(group_photo)
  

for i in range(len(names)):
  g = []
  h = []
  for j in range(len(names[i])):
    if j == 0:
      g.append(names[i][j] + " " +surnames[i][j] + " (Руководитель группы)")
    else:
      g.append(names[i][j] + " " +surnames[i][j])
    h.append("https://physics.itmo.ru/"+ rank[i][j])
  group_full_names.append(g)
  group_full_photo.append(h)  





###### публикации ########
# будут только ссылки на доки с публикациями 

tree = kod("https://physics.itmo.ru/ru/publications")
publi_links = tree.xpath('//div[@class="export-links"]/span[@class="papers-export-link export-gost"]/a/@href')
publi_links_other = tree.xpath('//div[@class="export-links"]/span[@class="papers-export-link export-txt"]/a/@href')
publi_links.append(publi_links_other[0])

###### стажировки школьников летняя практика ######

tree = kod("https://physics.itmo.ru/ru/internship/school/summer")

# добавить форматы
stage_sum_date = tree.xpath('//div[@class="field field--name-internship-date-text field--type-text-long field--label-hidden field--item"]/p/text()')
# летняя практика пройдёт
stage_sum_deadline = tree.xpath('//div[@class="field field--name-internship-date-end-text field--type-text-long field--label-hidden field--item"]/p/span[@class="internship-dates-yellow-date"]/text()')


# подать заявку 
stage_sum_podat = tree.xpath('//div[@class="field field--name-internship-date-button field--type-link field--label-hidden field--item"]/a/@href')

stage_sum_about_last_year = tree.xpath('//div[@class="field field--name-internship-project-desc field--type-text-long field--label-hidden field--item"]/p/text()')



# внутри уже есть год
stage_sum_comments = tree.xpath('//div[@class="field-content"]/p/text()')

# добавить команда проекта
stage_sum_team = tree.xpath('//div[@class="field field--name-internship-teams-person-text field--type-string field--label-hidden field--item"]/text()')


stage_sum_img_ruk = tree.xpath('//img[@width="300"]/@src')
stage_sum_name_ruk = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
stage_sum_surname_ruk = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')

stage_sum_rank = tree.xpath('//div[@class="field field--name-main-position field--type-entity-reference field--label-hidden field--item"]/text()')


########## стажировки школьников годовая практика #########

tree = kod("https://physics.itmo.ru/ru/internship/school/yearly")

stage_year_about_name = tree.xpath('//div[@class="field field--name-internship-project-name field--type-string field--label-hidden field--item"]/text()') 
stage_year_about = tree.xpath('//div[@class="field field--name-internship-project-desc field--type-text-long field--label-hidden field--item"]/text()')
stage_year_rank = tree.xpath('//div[@class="field--label"]/text()')
stage_year_uchastniki = tree.xpath('//div[@class="field field--name-internship-teams-person-text field--type-string field--label-above"]/div[@class="field--item"]/text()')
# убрать лишние элементы
stage_year_names = tree.xpath('//div[@class="field--item"]/a/text()')
stage_year_itogi = tree.xpath('//div[@class="field field--name-internship-results field--type-text-long field--label-above"]/div[@class="field--item"]/text()')
stage_year_video = tree.xpath('//iframe[@height="480"]/@src')

####### аспирантура #########
tree = kod("https://physics.itmo.ru/ru/admission/phd")

asp_kod_program = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
asp_names_program = tree.xpath('//div[@class="field field--name-description field--type-text-long field--label-hidden field--item"]/text()')
asp_date = tree.xpath('//div[@class="field field--name-adm-phd-date field--type-datetime field--label-hidden field--item"]/time/text()') 
asp_date_about = tree.xpath('//div[@class="field field--name-adm-phd-date-text field--type-string field--label-hidden field--item"]/text()')

asp_napravlenia = tree.xpath('//div[@class="node--wrap"]/h2[@class="node-title"]/span/text()')
asp_napravlenia_about = tree.xpath('//div[@class="field field--name-short-description field--type-text-long field--label-hidden field--item"]/p/text()')


asp_kontact_photo = tree.xpath('//div[@class="field field--name-photo field--type-image field--label-hidden field--item"]/img/@src')
asp_kontact_name = tree.xpath('//div[@class="personality-admission-name"]/text()')
asp_kontact_rank = tree.xpath('//div[@class="personality-admission-position"]/text()')
asp_kontact_pochta = tree.xpath('//div[@class="personality-admission-email"]/text()')
asp_kontact_number = tree.xpath('//div[@class="personality-admission-phone"]/a/text()')

# скорее всего здесь всё очень похоже с магистратурой, поэтому можно ввести функцию def 

########## магистратура #######






# tree.xpath('//div[@class=""]/')


# //ul[@class='facetOptions']/li/a[@role='checkbox']/@href

# print(semianars_topic1)
# print(seminars_names_speakers)
# print(semianars_topic2)
# print(semianars_time_date)
# print(semianars_time_time)
# print(semianrs_photo) #в photo_news
# print(sotrudniki_photo)
# print(sotrudniki_name1)
# print(sotrudniki_name2)
# print(sotrudniki_about)
# print(sotrudniki_about_links)
# print(videos_video)
# print(videos_about)
# print(videos_picture)
# print(vacancies_name)
# print(vacancies_topic)
# print(soft_name)
# print(soft_author)
# print(soft_links)
# print(smi_about)
# print(smi_links)

# print(group_name)
# print(group_photo)
# print(group_spisok_name)
# print(group_spisok_surname)
# print(group_spisok_rank) #в должности есть провфесор и Professor так можно разделить персон

# print(publi_links)


# print(stage_sum_date)
# print(stage_sum_deadline)
# print(stage_sum_podat)
# print(stage_sum_about_last_year)
# print(stage_sum_comments)
# print(stage_sum_team)
# print(stage_sum_img_ruk)
# print(stage_sum_name_ruk)
# print(stage_sum_surname_ruk)
# print(stage_sum_rank)

# print(stage_year_about_name)
# print(stage_year_rank)
# print(stage_year_uchastniki)
# print(stage_year_names)
# print(stage_year_about)
# print(stage_year_itogi)
# print(stage_year_video)


# print(asp_kod_program)
# print(asp_names_program)
# print(asp_date)
# print(asp_date_about)
# print(asp_napravlenia)
# print(asp_napravlenia_about)
# print(asp_kontact_photo)
# print(asp_kontact_name)
# print(asp_kontact_rank)
# print(asp_kontact_pochta)
# print(asp_kontact_number)
