# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Em_Wfv33C4EaHw2RrBwynwLNYHSXcD-M
"""

import requests
from urllib.request import urlopen
from lxml import html 


#пишешь по аналогии как я потому что так удобно ориентироваться
#все пометки, которые я делал например сдлеать словарь и тп ничего не делай



# это функция кода, т.е. выводит код lxml/html страницы

def kod(link):
  url = link
  headers = {'Content-Type': 'text/html',}
  response = requests.get(url, headers=headers)
  tree = html.fromstring(response.content)
  return tree

tree = kod("https://physics.itmo.ru/ru")


# Parsing the page
# (We need to use page.content rather than 
# page.text because html.fromstring implicitly
# expects bytes as input.)




####### Главная страница #######

# Get element using XPath

# Новости 

opisanie_news = tree.xpath('//div[@class="node--title"]/text()')
photo_news = tree.xpath('//img[@class="img-responsive"]/@src')
#//img[@class='photo-large']/@src

# print(opisanie_news)
# print(photo_news)


# надо писать окончательный путь
# Семинары 

semianrs_photo = tree.xpath('//img[@class="img-responsive"]/@src')
semianars_topic1 = tree.xpath('//div[@class="seminar-type-value"]/text()')
seminars_names_speakers = tree.xpath('//div[@class="external-speaker-wrapper"]/text()')
semianars_topic2 = tree.xpath('//div[@class="speaker-talk-name"]/text()')
semianars_time_date = tree.xpath('//div[@class="dte"]/text()')
semianars_time_time = tree.xpath('//div[@class="tme"]/text()')

# сделать функцию tree.path...


###### Сотрудники ######

tree = kod("https://physics.itmo.ru/ru/people")
sotrudniki_photo = tree.xpath('//img[@class="img-responsive"]/@src')
sotrudniki_name1 = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
sotrudniki_name2 = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')
sotrudniki_about = tree.xpath('//div[@class="field field--name-main-position field--type-entity-reference field--label-hidden field--item"]/text()')
sotrudniki_about_links = tree.xpath('//div[@class="node--wrap"]/@src')
# поискать


###### видео ######

tree = kod("https://physics.itmo.ru/ru/media/video")
videos_video = tree.xpath('//iframe[@width="854"]/@src')
videos_about = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')

###### вакансии ######

#создаётся словарь с названием вакансией и описанием 

tree = kod("https://physics.itmo.ru/ru/vacancies")
vacancies_name = tree.xpath('//a[@hreflang="ru"]/text()')
vacancies_topic = tree.xpath('//h3/text()')


####### софт ########
# создать словарь 

tree = kod("https://physics.itmo.ru/ru/soft")
soft_name = tree.xpath('//span[@class="field-content"]/text()')
soft_author = tree.xpath('//a[@hreflang="ru"]/text()')
soft_links = tree.xpath('//div[@class="field-content"]/@src') #не работает


####### сми ########


tree = kod("https://physics.itmo.ru/ru/media/press")
smi_name = tree.xpath('//div[@class="field field--name-type field--type-list-integer field--label-hidden field--item"]/text()')
smi_who = tree.xpath('//div[@class="field field--name-source field--type-entity-reference field--label-hidden field--item"]/text()')
smi_about = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
smi_date = tree.xpath('//time//text()')

###### научные группы #######

tree = kod("https://physics.itmo.ru/ru/research-groups")

group_name = tree.xpath('//div[@class="research-group-group-name"]/text()') #переделать в str и убрать пробелы и добаввить группа 
group_photo = tree.xpath('//img[@class="img-responsive"]/@src')

# надо разделить персоны на группы 
group_spisok_name = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
group_spisok_surname = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')
group_spisok_rank = tree.xpath('//div[@class="field field--name-main-position field--type-entity-reference field--label-hidden field--item"]/text()')
# надо сделать описание научной группы 


###### публикации ########
# будут только ссылки на доки с публикациями 

tree = kod("https://physics.itmo.ru/ru/publications")
publi_links = tree.xpath('//div[@class="export-links"]/span[@class="papers-export-link export-gost"]/a/@href')

###### стажировки школьников летняя практика ######

tree = kod("https://physics.itmo.ru/ru/internship/school/summer")

# добавить форматы
stage_sum_date = tree.xpath('//div[@class="field field--name-internship-date-text field--type-text-long field--label-hidden field--item"]/p/text()')
# летняя практика пройдёт
stage_sum_deadline = tree.xpath('//div[@class="field field--name-internship-date-end-text field--type-text-long field--label-hidden field--item"]/p/span[@class="internship-dates-yellow-date"]/text()')


# подать заявку 
stage_sum_podat = tree.xpath('//div[@class="field field--name-internship-date-button field--type-link field--label-hidden field--item"]/a/@href')

stage_sum_about_last_year = tree.xpath('//div[@class="field field--name-internship-project-desc field--type-text-long field--label-hidden field--item"]/p/text()')



# внутри уже есть год
stage_sum_comments = tree.xpath('//div[@class="field-content"]/p/text()')

# добавить команда проекта
stage_sum_team = tree.xpath('//div[@class="field field--name-internship-teams-person-text field--type-string field--label-hidden field--item"]/text()')


stage_sum_img_ruk = tree.xpath('//img[@width="300"]/@src')
stage_sum_name_ruk = tree.xpath('//div[@class="field field--name-name field--type-string field--label-hidden field--item"]/text()')
stage_sum_surname_ruk = tree.xpath('//div[@class="field field--name-second-name field--type-string field--label-hidden field--item"]/text()')

stage_sum_rank = tree.xpath('//div[@class="field field--name-main-position field--type-entity-reference field--label-hidden field--item"]/text()')


########## стажировки школьников годовая практика #########

tree = kod("https://physics.itmo.ru/ru/internship/school/yearly")

stage_year_about_name = tree.xpath('//div[@class="field field--name-internship-project-name field--type-string field--label-hidden field--item"]/text()') 
stage_year_about = tree.xpath('//div[@class="field field--name-internship-project-desc field--type-text-long field--label-hidden field--item"]/text()')
stage_year_rank = tree.xpath('//div[@class="field--label"]/text()')
stage_year_uchastniki = tree.xpath('//div[@class="field field--name-internship-teams-person-text field--type-string field--label-above"]/div[@class="field--item"]/text()')
# убрать лишние элементы
stage_year_names = tree.xpath('//div[@class="field--item"]/a/text()')
stage_year_itogi = tree.xpath('//div[@class="field field--name-internship-results field--type-text-long field--label-above"]/div[@class="field--item"]/text()')
stage_year_video = tree.xpath('//iframe[@height="480"]/@src')






# tree.xpath('//div[@class=""]/')


# //ul[@class='facetOptions']/li/a[@role='checkbox']/@href

# print(semianars_topic1)
# print(seminars_names_speakers)
# print(semianars_topic2)
# print(semianars_time_date)
# print(semianars_time_time)
# print(semianrs_photo) #в photo_news
# print(sotrudniki_photo)
# print(sotrudniki_name1)
# print(sotrudniki_name2)
# print(sotrudniki_about)
# print(sotrudniki_about_links)
# print(videos_video)
# print(videos_about)
# print(vacancies_name)
# print(vacancies_topic)
# print(soft_name)
# print(soft_author)
# print(soft_links)
# print(smi_who) #разные размерности
# print(smi_name) #разные размерности
# print(smi_about)
# print(smi_date)

# print(group_name)
# print(group_photo)
# print(group_spisok_name)
# print(group_spisok_surname)
# print(group_spisok_rank) #в должности есть провфесор и Professor так можно разделить персон

# print(publi_links)


# print(stage_sum_date)
# print(stage_sum_deadline)
# print(stage_sum_podat)
# print(stage_sum_about_last_year)
# print(stage_sum_comments)
# print(stage_sum_team)
# print(stage_sum_img_ruk)
# print(stage_sum_name_ruk)
# print(stage_sum_surname_ruk)
# print(stage_sum_rank)

# print(stage_year_about_name)
# print(stage_year_rank)
# print(stage_year_uchastniki)
# print(stage_year_names)
# print(stage_year_about)
# print(stage_year_itogi)
# print(stage_year_video)