# -*- coding: utf-8 -*-
"""api_general.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qWmUoD8JYngaku8KahBl9wydRpM8VNqj
"""

!pip install lxml
!pip install requests
!pip install beautifulsoup4
!pip install fake_useragent'

from bs4 import BeautifulSoup
from requests import get
import requests
from bs4 import BeautifulSoup
from fake_useragent import UserAgent
import re 

url = "https://physics.itmo.ru/ru"


a0 = UserAgent().chrome
page1 = requests.get(url, headers={'User-Agent': a0})
soup = BeautifulSoup(page1.text, "html.parser")

s1 = str(soup)
news = ""

# swiper-container
# if we need pagin
def swiper(i):
  j = i
  b = ""
  for k in range(len("swiper-container")):
    b = b + s1[i]
    i += 1
  i = j
  return b

k = 0
container = list = []

for i in range(len(s1)):
  if swiper(i) == "swiper-container" and k != 1:
    i += 1
    while swiper(i) != "swiper-container":
      i += 1
    container.append(i)
    k += 1
    break
  
i += 19
while swiper(i) != "If we need pagin":
  news = news + s1[i]
  i += 1

print(news)

news

